# Generated by Django 5.2.1 on 2025-05-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
